---
- name: Configure HAProxy Load Balancer
  hosts: load_balancers
  become: yes
  vars:
    backend_servers:
      - { name: web1, ip: 192.168.1.10 }
      - { name: web2, ip: 192.168.1.11 }

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

