---
- name: Dynamic Inventory from EC2
  hosts: localhost
  tasks:
    - name: Gather EC2 instances
      ec2_instance_facts:
        region: us-west-2
        filters:
          tag:Environment: production
      register: ec2_instances

    - name: Display instance information
      debug:
        var: ec2_instances.instances

